version: "3.3"

services:

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped 
    ports:
      - "8200:8096"
#     - "8920:8920" #optional      
    environment:
      - PUID=998
      - PGID=1000
      - TZ=Europe/Madrid
#     - UMASK_SET=022 #optional  
    volumes:
      - ./config:/config
      - ./tvshows:/data/tvshows  
      - ./movies:/data/movies   
      - ./music:/data/music
